[package]
name = "paleatra"
version = "0.1.0"
authors = ["Bexx Modebadze <bexxmodd@seas.upenn.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
structopt = "0.3"
indicatif = "0.16.0"